### ISSUE TITLE
burst photos

### ISSUE THREAD

**Issue by pokemonbattledroid** [kaytat/exiftool-scripts-for-takeout#1]
Hi,

I'm loving your scripts and has enabled me to go through quite a bit of my takeout photos.  I'm though coming across these burst cover photos like:
00000IMG_00000_BURST20180901101751159_COVER.jpg
They all have a consistent first part and the 8 digit date portion.  Is there a way to tweak the "looks like a date" one specifically for these files?  I've isolated them into a folder..

Would LOVE any help you can do, I've done a stab at the script, but I'm no programmer as such...

thank you in advance!!

Go

**Comment by kaytat** [comment]
Done. The new script is called burst.args and it's written specifically to address that example filename that you provided.

I've tested this locally but like the other "gambling" scripts, I would suggest making sure  you have backups of your images or remove the override tag so that if something goes wrong, you have something to go back to.

I've assumed that the time in the filename is of the form YYMMDD and then HHMMSSmmm where mmm is milliseconds. But when I look a little closer, I'm not sure that value is getting stored in the tags. I haven't looked closely to see if it's an issue with exiftool or just a limitation of the tags.

So just FYI that after doing this and everything seems to work ok, the images might still all be clumped together and in no particular order if sorted by time because they might all have the same time down to the second.

**Comment by pokemonbattledroid** [comment]
wow, amazing, thank you!!
--
iamgo.net
